[theme]
primaryColor = "#1e3a8a"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[ui]
hideTopBar = false

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
